# Generated by Django 5.2.1 on 2025-06-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_delete_perfilpaciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
