# Generated by Django 5.2.6 on 2025-09-14 21:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CitasMedicas',
            fields=[
                ('id_cita_medicas', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
                ('status_cita_medica', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('des_motivo_consulta_paciente', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('notas_medicas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citas_medicas',
                'ordering': ['fecha_consulta', 'hora_inicio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id_clinica', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('sitio_web', models.TextField(blank=True, null=True)),
                ('facebook', models.TextField(blank=True, null=True)),
                ('instagram', models.TextField(blank=True, null=True)),
                ('correo_electronico_clinica', models.TextField(blank=True, null=True)),
                ('telefono_clinica', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'factura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HorarioMedico',
            fields=[
                ('id_horario_medico', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_disponibilidad', models.CharField(blank=True, max_length=1, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horario_medico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MensajesNotificacion',
            fields=[
                ('id_mensaje_notificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mensajes_notificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id_metodopago', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipometodopago', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metodos_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('tel_emergencia', models.TextField(blank=True, null=True)),
                ('contacto_emergencia', models.TextField(blank=True, null=True)),
                ('poliza_vigente', models.CharField(blank=True, max_length=1, null=True)),
                ('no_carne_poliza', models.TextField(blank=True, null=True)),
                ('no_poliza', models.TextField(blank=True, null=True)),
                ('nombre_aseguradora', models.TextField(blank=True, null=True)),
                ('nombre_responsable', models.TextField(blank=True, null=True)),
                ('fk_cuadro_clinico', models.BigIntegerField(blank=True, null=True)),
                ('dui', models.CharField(default='00000000-0', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RankingMedico',
            fields=[
                ('id_ranking_medico', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel_de_ranking', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ranking_medico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ValoracionConsulta',
            fields=[
                ('id_valoracion_consulta', models.BigAutoField(primary_key=True, serialize=False)),
                ('calificacion_consulta', models.IntegerField(blank=True, null=True)),
                ('resena', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'valoracion_consulta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id_consulta_medica', models.BigAutoField(primary_key=True, serialize=False)),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('documentos_adjuntos', models.FileField(blank=True, null=True, upload_to='consultas/documentos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fk_cita', models.OneToOneField(db_column='fk_cita', on_delete=django.db.models.deletion.CASCADE, related_name='consulta_medica', to='bd.citasmedicas')),
            ],
            options={
                'db_table': 'consulta_medica',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='citasmedicas',
            name='fk_factura',
            field=models.ForeignKey(blank=True, db_column='fk_factura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.factura'),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.BigAutoField(primary_key=True, serialize=False)),
                ('dui', models.TextField(blank=True, null=True)),
                ('no_jvpm', models.TextField(blank=True, null=True)),
                ('especialidad', models.TextField(blank=True, null=True)),
                ('sub_especialidad_1', models.TextField(blank=True, null=True)),
                ('sub_especialidad_2', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fk_clinica', models.ForeignKey(blank=True, db_column='fk_clinica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.clinica')),
                ('fk_horario_medico', models.ForeignKey(blank=True, db_column='fk_horario_medico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.horariomedico')),
                ('fk_ranking_medico', models.ForeignKey(blank=True, db_column='fk_ranking_medico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.rankingmedico')),
            ],
            options={
                'db_table': 'medico',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='citasmedicas',
            name='fk_medico',
            field=models.ForeignKey(blank=True, db_column='fk_medico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.medico'),
        ),
        migrations.AddField(
            model_name='citasmedicas',
            name='fk_mensajes_notificacion',
            field=models.ForeignKey(blank=True, db_column='fk_mensajes_notificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.mensajesnotificacion'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fk_metodopago',
            field=models.ForeignKey(blank=True, db_column='fk_metodopago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.metodospago'),
        ),
        migrations.AddField(
            model_name='citasmedicas',
            name='fk_paciente',
            field=models.ForeignKey(blank=True, db_column='fk_paciente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.paciente'),
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id_receta_medica', models.BigAutoField(primary_key=True, serialize=False)),
                ('medicamento', models.TextField(blank=True, null=True)),
                ('via_administracion', models.TextField(blank=True, null=True)),
                ('dosis', models.TextField(blank=True, null=True)),
                ('fecha_inicio_tratamiento', models.DateField(blank=True, null=True)),
                ('fecha_fin_tratamiento', models.DateField(blank=True, null=True)),
                ('fk_citas_medicas', models.ForeignKey(blank=True, db_column='fk_citas_medicas', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.citasmedicas')),
            ],
            options={
                'db_table': 'receta_medica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('status_plataforma', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('fk_admin', models.ForeignKey(blank=True, db_column='fk_admin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.admin')),
                ('fk_medico', models.ForeignKey(blank=True, db_column='fk_medico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.medico')),
                ('fk_paciente', models.ForeignKey(blank=True, db_column='fk_paciente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.paciente')),
                ('fk_rol', models.ForeignKey(blank=True, db_column='fk_rol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.rol')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='rankingmedico',
            name='fk_valoracion_consulta',
            field=models.ForeignKey(blank=True, db_column='fk_valoracion_consulta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.valoracionconsulta'),
        ),
    ]
