# Generated by Django 5.2.3 on 2025-06-11 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('status_plataforma', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CitasMedicas',
            fields=[
                ('id_cita_medicas', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
                ('status_cita_medica', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('des_motivo_consulta_paciente', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('notas_medicas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citas_medicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id_clinica', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('sitio_web', models.TextField(blank=True, null=True)),
                ('facebook', models.TextField(blank=True, null=True)),
                ('instagram', models.TextField(blank=True, null=True)),
                ('correo_electronico_clinica', models.TextField(blank=True, null=True)),
                ('telefono_clinica', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioMedico',
            fields=[
                ('id_horario_medico', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_disponibilidad', models.CharField(blank=True, max_length=1, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horario_medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.BigAutoField(primary_key=True, serialize=False)),
                ('dui', models.TextField(blank=True, null=True)),
                ('no_jvpm', models.TextField(blank=True, null=True)),
                ('especialidad', models.TextField(blank=True, null=True)),
                ('sub_especialidad_1', models.TextField(blank=True, null=True)),
                ('sub_especialidad_2', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MensajesNotificacion',
            fields=[
                ('id_mensaje_notificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mensajes_notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id_metodopago', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipometodopago', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metodos_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('tel_emergencia', models.TextField(blank=True, null=True)),
                ('contacto_emergencia', models.TextField(blank=True, null=True)),
                ('poliza_vigente', models.CharField(blank=True, max_length=1, null=True)),
                ('no_carne_poliza', models.TextField(blank=True, null=True)),
                ('no_poliza', models.TextField(blank=True, null=True)),
                ('nombre_aseguradora', models.TextField(blank=True, null=True)),
                ('nombre_responsable', models.TextField(blank=True, null=True)),
                ('fk_cuadro_clinico', models.BigIntegerField(blank=True, null=True)),
                ('dui', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RankingMedico',
            fields=[
                ('id_ranking_medico', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel_de_ranking', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ranking_medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id_receta_medica', models.BigAutoField(primary_key=True, serialize=False)),
                ('medicamento', models.TextField(blank=True, null=True)),
                ('via_administracion', models.TextField(blank=True, null=True)),
                ('dosis', models.TextField(blank=True, null=True)),
                ('fecha_inicio_tratamiento', models.DateField(blank=True, null=True)),
                ('fecha_fin_tratamiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receta_medica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValoracionConsulta',
            fields=[
                ('id_valoracion_consulta', models.BigAutoField(primary_key=True, serialize=False)),
                ('calificacion_consulta', models.IntegerField(blank=True, null=True)),
                ('resena', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'valoracion_consulta',
                'managed': False,
            },
        ),
    ]
