# Generated by Django 5.2.7 on 2025-10-05 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolizaSeguro',
            fields=[
                ('id_poliza', models.BigAutoField(primary_key=True, serialize=False)),
                ('compania_aseguradora', models.CharField(max_length=150)),
                ('numero_poliza', models.CharField(max_length=50, unique=True)),
                ('fecha_vigencia', models.DateField()),
                ('tipo_cobertura', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='bd.paciente')),
            ],
            options={
                'db_table': 'poliza_seguro',
                'managed': True,
            },
        ),
    ]
