# Generated by Django 5.2.6 on 2025-10-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='valoracionconsulta',
            name='fk_cita',
            field=models.ForeignKey(blank=True, db_column='fk_cita', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bd.citasmedicas'),
        ),
    ]
