# Generated by Django 5.2.1 on 2025-06-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_alter_paciente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dui',
            field=models.CharField(default='00000000-0', max_length=10, unique=True),
        ),
    ]
