# Generated by Django 5.2.7 on 2025-10-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_polizaseguro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polizaseguro',
            options={'managed': True, 'verbose_name': 'Póliza de Seguro', 'verbose_name_plural': 'Pólizas de Seguros'},
        ),
    ]
