# Generated by Django 5.2.6 on 2025-10-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_clinica_municipio_valoracionconsulta_fk_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasmedicas',
            name='cancelado_por',
            field=models.CharField(blank=True, choices=[('medico', 'Médico'), ('paciente', 'Paciente')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='citasmedicas',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='documentos_adjuntos',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
