# Generated by Django 4.2.13 on 2025-10-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_citasmedicas_cancelado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='archivos_receta',
            field=models.FileField(blank=True, null=True, upload_to='recetas/'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='dosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='fecha_fin_tratamiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='fecha_inicio_tratamiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='medicamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='via_administracion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
