# Generated by Django 5.2.1 on 2025-06-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_alter_citasmedicas_options_alter_paciente_dui'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citasmedicas',
            options={'managed': False, 'ordering': ['fecha_consulta', 'hora_inicio']},
        ),
    ]
