# Generated by Django 4.2.13 on 2025-10-06 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0004_consultamedica_archivos_receta_consultamedica_dosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoClinico',
            fields=[
                ('id_seguimiento_clinico', models.BigAutoField(primary_key=True, serialize=False)),
                ('diagnostico_final', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('medicamento', models.TextField(blank=True, null=True)),
                ('dosis', models.TextField(blank=True, null=True)),
                ('frecuencia', models.TextField(blank=True, null=True)),
                ('duracion', models.TextField(blank=True, null=True)),
                ('archivos_receta', models.FileField(blank=True, null=True, upload_to='recetas_seguimiento/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('programar_nueva_consulta', models.BooleanField(default=False)),
                ('fecha_nueva_consulta', models.DateField(blank=True, null=True)),
                ('hora_nueva_consulta', models.TimeField(blank=True, null=True)),
                ('notas_nueva_consulta', models.TextField(blank=True, null=True)),
                ('fk_cita', models.ForeignKey(db_column='fk_cita', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='bd.citasmedicas')),
                ('fk_medico', models.ForeignKey(db_column='fk_medico', on_delete=django.db.models.deletion.CASCADE, to='bd.medico')),
                ('fk_paciente', models.ForeignKey(db_column='fk_paciente', on_delete=django.db.models.deletion.CASCADE, to='bd.paciente')),
            ],
            options={
                'db_table': 'seguimiento_clinico',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConsultaSeguimiento',
            fields=[
                ('id_consulta_seguimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('sintomas_actuales', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('comparacion_primera_consulta', models.TextField(blank=True, null=True)),
                ('mejoro_salud', models.CharField(blank=True, choices=[('S', 'Sí'), ('N', 'No'), ('P', 'Parcialmente')], max_length=1, null=True)),
                ('necesita_receta_diferente', models.BooleanField(default=False)),
                ('medicamento', models.TextField(blank=True, null=True)),
                ('dosis', models.TextField(blank=True, null=True)),
                ('frecuencia', models.TextField(blank=True, null=True)),
                ('duracion', models.TextField(blank=True, null=True)),
                ('archivos_receta', models.FileField(blank=True, null=True, upload_to='recetas_consulta_seguimiento/')),
                ('documentos_adjuntos', models.FileField(blank=True, null=True, upload_to='documentos_seguimiento/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('consulta_completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('fk_medico', models.ForeignKey(db_column='fk_medico', on_delete=django.db.models.deletion.CASCADE, to='bd.medico')),
                ('fk_paciente', models.ForeignKey(db_column='fk_paciente', on_delete=django.db.models.deletion.CASCADE, to='bd.paciente')),
                ('fk_seguimiento_anterior', models.ForeignKey(blank=True, db_column='fk_seguimiento_anterior', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_seguimiento', to='bd.seguimientoclinico')),
            ],
            options={
                'db_table': 'consulta_seguimiento',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
    ]
