# Generated by Django 4.2.13 on 2025-10-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0005_seguimientoclinico_consultaseguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaseguimiento',
            name='fecha_nueva_cita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultaseguimiento',
            name='hora_nueva_cita',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultaseguimiento',
            name='motivo_nueva_cita',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultaseguimiento',
            name='programar_nueva_cita',
            field=models.BooleanField(default=False),
        ),
    ]
