# Generated by Django 4.2.13 on 2025-10-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0004_contactoemergencia'),
        ('bd', '0006_add_nueva_cita_fields'),
    ]

    operations = [
    ]
