# Generated by Django 4.2.13 on 2025-10-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0007_merge_20251006_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultamedica',
            name='documentos_adjuntos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
