# Generated by Django 4.2.13 on 2025-10-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0008_change_documentos_to_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultamedica',
            name='documentos_adjuntos',
            field=models.URLField(blank=True, null=True),
        ),
    ]
