# Generated by Django 4.2.13 on 2025-10-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0009_change_to_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultamedica',
            name='documentos_adjuntos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
