# Generated by Django 4.2.13 on 2025-10-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0010_back_to_text_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
