# Generated by Django 4.2.13 on 2025-10-11 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0011_add_2fa_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polizaseguro',
            old_name='id_poliza',
            new_name='id',
        ),
        migrations.AlterModelTable(
            name='polizaseguro',
            table='bd_polizaseguro',
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
