# Generated by Django 4.2.13 on 2025-10-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0012_rename_id_poliza_polizaseguro_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
