# Generated by Django 4.2.13 on 2025-10-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0013_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasmedicas',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='citasmedicas',
            name='monto_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='citasmedicas',
            name='pago_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metodospago',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='metodospago',
            name='fecha_expiracion',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='metodospago',
            name='nombre_titular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metodospago',
            name='numero_tarjeta',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='metodospago',
            name='tipo_tarjeta',
            field=models.CharField(blank=True, choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=20, null=True),
        ),
    ]
