# Generated by Django 4.2.13 on 2025-10-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0014_citasmedicas_metodo_pago_citasmedicas_monto_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='precio_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio base de la consulta médica', max_digits=10, null=True),
        ),
    ]
