# Generated by Django 4.2.13 on 2025-10-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0015_medico_precio_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosAdicionales',
            fields=[
                ('id_gastos_adicionales', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Descripción del gasto adicional (ej: Examen de sangre, Medicamento, etc.)')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del gasto adicional', max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False)),
                ('fk_cita', models.ForeignKey(db_column='fk_cita', on_delete=django.db.models.deletion.CASCADE, related_name='gastos_adicionales', to='bd.citasmedicas')),
            ],
            options={
                'db_table': 'gastos_adicionales',
                'ordering': ['fecha_creacion'],
                'managed': True,
            },
        ),
    ]
