# Generated by Django 4.2.13 on 2025-10-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0016_gastosadicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultamedica',
            name='archivos_receta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
