# Generated by Django 4.2.13 on 2025-10-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0017_alter_consultamedica_archivos_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='codigo_generacion',
            field=models.CharField(blank=True, help_text='Código de generación UUID', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='documento_interno',
            field=models.CharField(blank=True, help_text='Documento interno secuencial', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_control',
            field=models.CharField(blank=True, help_text='Número de control DTE-01- + letras/números aleatorios', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='sello_recepcion',
            field=models.CharField(blank=True, help_text='Sello de recepción con año + números/letras aleatorias', max_length=50, null=True),
        ),
    ]
