# Generated by Django 4.2.13 on 2025-10-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0018_factura_codigo_generacion_factura_documento_interno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodospago',
            name='tipometodopago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=20, null=True),
        ),
    ]
