# Generated by Django 4.2.13 on 2025-10-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0019_alter_metodospago_tipometodopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.TextField(blank=True, help_text='Foto de perfil en formato base64', null=True),
        ),
    ]
