# Generated by Django 4.2.13 on 2025-10-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0020_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='titulo_medico',
            field=models.TextField(blank=True, help_text='Título médico en formato base64', null=True),
        ),
    ]
