# Generated by Django 5.2.6 on 2025-10-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0021_medico_titulo_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citasmedicas',
            name='pago_confirmado',
            field=models.BooleanField(default=False, help_text='Indica si el pago ha sido confirmado'),
        ),
    ]
